name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: Checkout the code
    
    - uses: actions/pages-build@master
      name: Build
      
    - uses: actions/pages-deploy@master
      name: Deploy
